# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodioKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(help_text='Application Name (as specified in Podio)', max_length=150)),
                ('client_id', models.CharField(help_text='Client ID (as specified in Podio)', max_length=150)),
                ('client_secret', models.CharField(help_text='Client Secret (as specified in Podio)', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PodioUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Username for the Podio User', max_length=150)),
                ('user_password', models.CharField(help_text='Password for the Podio User', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='podiokey',
            name='podio_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podiosync.PodioUser'),
        ),
    ]
