# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podiosync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podiokey',
            name='key_nickname',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
