# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podiosync', '0002_podiokey_key_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('application_name', models.CharField(max_length=255)),
                ('application_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
