# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podiosync', '0003_applicationsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsync',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
